kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  # -- Default config --
  # this will break on minikube restart
  # local:
  #   path: /mnt
  # -- useing hostPath with hard path --
  # hostPath:
  #   path: /Users/aernan/workspace/ci-cd-on-demand/jenkins/persistent_volume
  # -- using hostPath with environemtn variable --
  # must set environment variable for substition
  # export REPO_PATH="/Users/aernan/workspace/ci-cd-on-demand"
  hostPath:
    path: ${REPO_PATH}/jenkins/persistent_volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          # Important Note: Replace 'worker-node01' with any one of your cluster worker nodes hostname.
          values:
          # Default value:
          # - worker-node01
          # updated for minikube
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
